import {Support} from '../models'

export const defaultSupports: Support[] = [
  {
    id: 1,
    level: 0,
    title: 'Кактус',
    description: 'Поглощает углекислый газ и выделяет кислород',
    has: false,
    cost: 5000,
    increase: 1,
    multiplier: 2,
  },
  {
    id: 2,
    level: 0,
    title: 'Буквоед',
    description: 'Читает умные книги ночью и утром',
    has: false,
    cost: 10000,
    increase: 2,
    multiplier: 2,
  },
  {
    id: 3,
    level: 0,
    title: 'Очепяточник',
    description: 'Ловко исправляет опечатки и грамматические ошибки',
    has: false,
    cost: 15000,
    increase: 4,
    multiplier: 2,
  },
  {
    id: 4,
    level: 0,
    title: 'Идеягенератор',
    description: 'Всегда приносит свежие идеи для вашего кода',
    has: false,
    cost: 25000,
    increase: 8,
    multiplier: 2,
  },
  {
    id: 5,
    level: 0,
    title: 'Лампа гуру',
    description: 'Освещает самые темные уголки вашего кода',
    has: false,
    cost: 50000,
    increase: 12,
    multiplier: 4,
  },
  {
    id: 6,
    level: 0,
    title: 'Курсор-ракета',
    description: 'Делает ваш курсор невероятно быстрым',
    has: false,
    cost: 100000,
    increase: 20,
    multiplier: 4,
  },
]
